import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "./component/Navber";
import Banner from "./component/Banner";
import Feature from "./component/Feature";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Chorcha",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Navbar */}
        <Navber></Navber>


        {/* Page Content */}
        {children}
      </body>
    </html>
  );
}
